# model settings
norm_cfg: &norm_cfg
  type: SyncBN
  requires_grad: true

data_preprocessor: &data_preprocessor
  type: SegDataPreProcessor
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  bgr_to_rgb: true
  pad_val: 0
  seg_pad_val: 255

model:
  type: EncoderDecoder
  data_preprocessor: *data_preprocessor
  pretrained: models/hrnetv2_w18.pth
  backbone:
    type: HRNet
    norm_cfg: *norm_cfg
    norm_eval: false
    extra:
      stage1:
        num_modules: 1
        num_branches: 1
        block: BOTTLENECK
        num_blocks: [4]
        num_channels: [64]
      stage2:
        num_modules: 1
        num_branches: 2
        block: BASIC
        num_blocks: [4, 4]
        num_channels: [18, 36]
      stage3:
        num_modules: 4
        num_branches: 3
        block: BASIC
        num_blocks: [4, 4, 4]
        num_channels: [18, 36, 72]
      stage4:
        num_modules: 3
        num_branches: 4
        block: BASIC
        num_blocks: [4, 4, 4, 4]
        num_channels: [18, 36, 72, 144]
  decode_head:
    type: FCNHead
    in_channels: [18, 36, 72, 144]
    in_index: [0, 1, 2, 3]
    channels: 270  # sum([18, 36, 72, 144])
    input_transform: resize_concat
    kernel_size: 1
    num_convs: 1
    concat_input: false
    dropout_ratio: -1
    num_classes: 19
    norm_cfg: *norm_cfg
    align_corners: false
    loss_decode:
      type: CrossEntropyLoss
      use_sigmoid: false
      loss_weight: 1.0
  # model training and testing settings
  train_cfg: {}
  test_cfg:
    mode: whole
