
norm_cfg: &norm_cfg
  type: SyncBN
  requires_grad: true

backbone_norm_cfg: &backbone_norm_cfg
  type: LN
  requires_grad: true

data_preprocessor: &data_preprocessor
  type: SegDataPreProcessor
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  bgr_to_rgb: true
  pad_val: 0
  seg_pad_val: 255

model:
  type: EncoderDecoder
  data_preprocessor: *data_preprocessor
  pretrained: null
  backbone:
    type: SwinTransformer
    pretrain_img_size: 224
    embed_dims: 96
    patch_size: 4
    window_size: 7
    mlp_ratio: 4
    depths: [2, 2, 6, 2]
    num_heads: [3, 6, 12, 24]
    strides: [4, 2, 2, 2]
    out_indices: [0, 1, 2, 3]
    qkv_bias: true
    qk_scale: null
    patch_norm: true
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.3
    use_abs_pos_embed: false
    act_cfg:
      type: GELU
    norm_cfg: *backbone_norm_cfg
  decode_head:
    type: UPerHead
    in_channels: [96, 192, 384, 768]
    in_index: [0, 1, 2, 3]
    pool_scales: [1, 2, 3, 6]
    channels: 512
    dropout_ratio: 0.1
    num_classes: 19
    norm_cfg: *norm_cfg
    align_corners: false
    loss_decode:
      type: CrossEntropyLoss
      use_sigmoid: false
      loss_weight: 1.0
  auxiliary_head:
    type: FCNHead
    in_channels: 384
    in_index: 2
    channels: 256
    num_convs: 1
    concat_input: false
    dropout_ratio: 0.1
    num_classes: 19
    norm_cfg: *norm_cfg
    align_corners: false
    loss_decode:
      type: CrossEntropyLoss
      use_sigmoid: false
      loss_weight: 0.4
  train_cfg: {}
  test_cfg:
    mode: whole
