_base_:
  - ../_base_/models/segformer_mit-b0.yaml
  - ../_base_/datasets/A0belt_images.yaml
  - ../_base_/default_runtime.yaml
  - ../_base_/schedules/schedule_20k.yaml

crop_size: &crop_size [512, 512]

data_preprocessor: &data_preprocessor
  size: *crop_size

model:
  data_preprocessor: *data_preprocessor
  backbone:
    init_cfg:
      type: Pretrained
      checkpoint: models/mit_b2.pth
    num_layers: [3, 4, 6, 3]
    embed_dims: 64
  decode_head:
    in_channels: [64, 128, 320, 512]
    num_classes: 6

optim_wrapper:
  _delete_: true
  type: OptimWrapper
  optimizer:
    type: AdamW
    lr: 0.00006
    betas: [0.9, 0.999]
    weight_decay: 0.01
  paramwise_cfg:
    custom_keys:
      pos_block:
        decay_mult: 0.0
      norm:
        decay_mult: 0.0
      head:
        lr_mult: 10.0

param_scheduler:
  - type: LinearLR
    start_factor: 1.0e-06
    by_epoch: false
    begin: 0
    end: 1500
  - type: PolyLR
    eta_min: 0.0
    power: 1.0
    begin: 1500
    end: 20000
    by_epoch: false

train_dataloader:
  batch_size: 2
  num_workers: 2

val_dataloader: &val_dataloader
  batch_size: 1
  num_workers: 4

test_dataloader: *val_dataloader
