_base_:
  - ../_base_/models/upernet_swin.yaml
  - ../_base_/datasets/A0belt_images.yaml
  - ../_base_/default_runtime.yaml
  - ../_base_/schedules/schedule_20k.yaml

crop_size: &crop_size [512, 512]

data_preprocessor: &data_preprocessor
  size: *crop_size

model:
  data_preprocessor: *data_preprocessor
  backbone:
    init_cfg:
      type: Pretrained
      checkpoint: models/swin_tiny_patch4_window7_224.pth
    embed_dims: 96
    depths: [2, 2, 6, 2]
    num_heads: [3, 6, 12, 24]
    window_size: 7
    use_abs_pos_embed: false
    drop_path_rate: 0.3
    patch_norm: true
  decode_head:
    in_channels: [96, 192, 384, 768]
    num_classes: 6
  auxiliary_head:
    in_channels: 384
    num_classes: 6

optim_wrapper:
  _delete_: true
  type: OptimWrapper
  optimizer:
    type: AdamW
    lr: 0.00006
    betas: [0.9, 0.999]
    weight_decay: 0.01
  paramwise_cfg:
    custom_keys:
      absolute_pos_embed:
        decay_mult: 0.0
      relative_position_bias_table:
        decay_mult: 0.0
      norm:
        decay_mult: 0.0

param_scheduler:
  - type: LinearLR
    start_factor: 1.0e-06
    by_epoch: false
    begin: 0
    end: 1500
  - type: PolyLR
    eta_min: 0.0
    power: 1.0
    begin: 1500
    end: 20000
    by_epoch: false

train_dataloader:
  batch_size: 2

val_dataloader: &val_dataloader
  batch_size: 1

test_dataloader: *val_dataloader

