_base_: [
    '../../flabplatform/flabseg/configs/hrnet/fcn_hr18_4xb2-20k_A0belt_images-512x1024.yaml'
]

model: &_model
    type: EncoderDecoder
    decode_head:
        num_classes: 6

training:
    algoParams: 
        device: 0
        model: *_model

train_cfg:
  type: IterBasedTrainLoop
  max_iters: 100
  val_interval: 100
