# dataset settings
dataset_type: &_dataset_type 'LabelmeDetDataset'

# Example to use different file client
# Method 1: simply set the data root and let the file I/O module
# automatically infer from prefix (not support LMDB and Memcache yet)

# data_root = 's3://openmmlab/datasets/detection/coco/'


backend_args: &_backend_args null

batch_size: &_batch_size 2
num_workers: &_num_workers 4

labels: &_labels [
        'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train',
        'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign',
        'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep',
        'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella',
        'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard',
        'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard',
        'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork',
        'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange',
        'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair',
        'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv',
        'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave',
        'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase',
        'scissors', 'teddy bear', 'hair drier', 'toothbrush'
]

train_pipeline: &_train_pipeline
    - type: 'LoadImageFromFile'
      backend_args: *_backend_args
    - type: 'LoadAnnotations'
      with_bbox: true
    - type: 'Resize'
      scale: !!python/tuple [1333, 800]
      keep_ratio: true
    - type: 'RandomFlip'
      prob: 0.5
    - type: 'PackDetInputs'

test_pipeline: &_test_pipeline
    - type: 'LoadImageFromFile'
      backend_args: *_backend_args
    - type: 'Resize'
      scale: !!python/tuple [1333, 800]
      keep_ratio: true
    - type: 'LoadAnnotations'
      with_bbox: true
    - type: 'PackDetInputs'
      meta_keys: ['img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor']

train_dataloader:
    batch_size: *_batch_size
    num_workers: *_num_workers
    persistent_workers: true
    sampler:
        type: 'DefaultSampler'
    batch_sampler:
        type: 'AspectRatioBatchSampler'
    dataset:
        type: *_dataset_type
        data_root: 'datasets/coco8/'
        # ann_file: 'images/train.json'
        metainfo:
            classes: *_labels
        data_prefix:
            img: ['images/train/']
        filter_cfg:
            filter_empty_gt: true
            min_size: 32
        pipeline: *_train_pipeline
        backend_args: *_backend_args

val_dataloader: &_val_dataloader
    batch_size: *_batch_size
    num_workers: *_num_workers
    persistent_workers: true
    drop_last: false
    sampler:
        type: 'DefaultSampler'
        shuffle: false
    dataset:
        type: *_dataset_type
        data_root: 'datasets/coco8/'
        # ann_file: 'images/val.json'
        metainfo:
            classes: *_labels
        data_prefix:
            img: ['images/val/']
        test_mode: true
        pipeline: *_test_pipeline
        backend_args: *_backend_args

test_dataloader: *_val_dataloader

val_evaluator: &_val_evaluator
    type: 'MMEvaluator'
    # ann_file: 'datasets/coco8/images/val.json'
    # metric: 'bbox'
    # backend_args: *_backend_args