default_scope: 'flabplatform.flabdet'

default_hooks:
  timer:
    type: 'IterTimerHook'
  logger:
    type: 'LoggerHook'
    interval: 50
  param_scheduler:
    type: 'ParamSchedulerHook'
  checkpoint:
    type: 'CheckpointHook'
    interval: 1
  sampler_seed:
    type: 'DistSamplerSeedHook'
  visualization:
    type: 'DetVisualizationHook'

vis_backends: &_vis_backends
  - type: 'LocalVisBackend'

visualizer:
  type: 'DetLocalVisualizer'
  vis_backends: *_vis_backends
  name: 'visualizer'

log_processor:
  type: 'LogProcessor'
  window_size: 50
  by_epoch: True

log_level: 'INFO'
load_from: null
resume: false