_base_: [
    '../../flabplatform/flabseg/configs/swin/swin-base-patch4-window7-in1k-pre_upernet_8xb2-20k_A0belt_images-512x512.yaml'
]

model: &_model
    type: EncoderDecoder
    decode_head:
        num_classes: 6

training:
    algoParams: 
        device: 0
        model: *_model