_base_: [
    './dab-detr_r50_8xb2-50e_coco.yaml'
]

model: &_model
    type: 'DABDETR'
    num_queries: 300

training:
    algoParams: 
        device: 0
        model: *_model

optim_wrapper:
    type: 'OptimWrapper'
    optimizer:
        type: 'AdamW'
        lr: 0.0001
        weight_decay: 0.0001

max_epochs: &_max_epochs 2


randomness:
    deterministic: False # (bool) whether to enable deterministic mode
    seed: 0 # (int) random seed for reproducibility
